### ISSUE TITLE
UnsupportedEncodingException: text/x-brat

### ISSUE THREAD

**Issue by Jongmassey** [GateNLP/gateplugin-Format_Brat#3]
Trying to import brat standoff document in .txt format with .ann file alongside. Set mime time to text/x-brat as per instructions, document fails to load with 
`
Resource could not be created!
gate.creole.ResourceInstantiationException: DocumentImpl.init: java.io.UnsupportedEncodingException: text/x-brat
`
`GATE 8.6 build 86a246c started at Wed Jun 19 13:40:58 BST 2019
and using Java 1.8.0_212 AdoptOpenJDK on Windows 10 amd64 10.0.
CREOLE plugin loaded: Format: brat standoff 1.0
gate.creole.ResourceInstantiationException: DocumentImpl.init: java.io.UnsupportedEncodingException: text/x-brat
	at gate.corpora.DocumentImpl.init(DocumentImpl.java:259)
	at gate.Factory.createResource(Factory.java:430)
	at gate.gui.NewResourceDialog$4.run(NewResourceDialog.java:270)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by greenwoodma** [comment]
Daft question, but is there any chance you put `text/x-brat` into the encoding parameter field instead of the mime type field?

**Comment by Jongmassey** [comment]
Well, I'm a monumental wally. That's exactly it! Thanks for the fast reply
